### ISSUE TITLE
Base ticket for ui-kit release checklist (CLONE - DO NOT CLOSE)

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-ui-kit#44]
- [ ] (DEV) Close or defer all tickets in the epics (code complete/scope closure) - code freeze
- [ ] (DEV) Create release candidate branch (branching, tagging)
- [ ] (Business Owner) Identify destination & distribution targets (communications, announcements)
- [ ] (PM) Dependent releases have been identified and e2e acceptance tests pass in a production environment (list them here):
        - [ ] (default) no dependent releases
- [ ] (SRE) Ensure SRE pipelines are in place
- [ ] (DEV) storybook instances have been created for all components
- [ ] (DEV) Create readme in git repo (scope closure)
- [ ] (DEV) ensure changelog is in place
- [ ] (DEV) Browser testing has passed for all supported browsers
- [ ] (DEV) Documentation updates are in place (docs team)
